### ISSUE TITLE
chinese2English NMT

### ISSUE THREAD

**Issue by perveil** [Helsinki-NLP/Opus-MT#32]
i want to find a chinese2English NMT ,but  i can `t find in these model you provide,can you give me a link?

**Comment by jorgtied** [comment]
Here is one you can use: https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/zho-eng

**Comment by perveil** [comment]
Thanks，where is the dataset that model trained？&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Helsinki-NLP/Opus-MT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月26日(星期四) 上午6:02
收件人:&nbsp;"Helsinki-NLP/Opus-MT"<Opus-MT@noreply.github.com&gt;;
抄送:&nbsp;"986778566"<986778566@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Helsinki-NLP/Opus-MT] chinese2English NMT (#32)





 
Here is one you can use: https://github.com/Helsinki-NLP/Tatoeba-Challenge/tree/master/models/zho-eng

**Comment by jorgtied** [comment]
Using the data set published here: https://github.com/Helsinki-NLP/Tatoeba-Challenge/

**Comment by perveil** [comment]
Thanks，you have done an awosome work!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Helsinki-NLP/Opus-MT"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 下午3:31
收件人:&nbsp;"Helsinki-NLP/Opus-MT"<Opus-MT@noreply.github.com&gt;;
抄送:&nbsp;"986778566"<986778566@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Helsinki-NLP/Opus-MT] chinese2English NMT (#32)





 
Using the data set published here: https://github.com/Helsinki-NLP/Tatoeba-Challenge/
