### ISSUE TITLE
opusmt.wmflabs.org down

### ISSUE THREAD

**Issue by jhsoby** [Helsinki-NLP/Opus-MT#43]
Someone reported in a Telegram chat that the instance at opusmt.wmflabs.org is down (502 Bad Gateway). Not sure if this is the correct place to report it, but hopefully someone here knows how to fix it.

**Comment by kartikm** [comment]
Fixed now. Thanks for reporting!

**Comment by jhsoby** [comment]
Thank you very much @kartikm !
