### ISSUE TITLE
'en-jap' model. What is 'jap'?

### ISSUE THREAD

**Issue by OlegVasilyev4096** [Helsinki-NLP/Opus-MT#52]
Hi, About 'en-jap' model: Could not find 'jap' ISO codes. Is it is the same as 'ja' (in Helsinki-NLP/opus-mt-en-jap)?
Is there a doc listing all the codes used here? Assuming that 'jap' is the same as 'ja', and using the demo huggingface.co/Helsinki-NLP/opus-mt- for en-jap and ja-en, I got several roundtrip translations pasted below.
From those, I am still not sure if 'jap' is the same as 'ja'. 
Thankful for any pointer to a doc with the language codes you use.

_“My name is Wolfgang and I live in Berlin” -> “わが 名 は シナル と い い , また " わたし は 永遠 に 生き る " と .” -> “I say to you, " said Jesus, "I am going to make a helper for him, as a complement of him.”

“In winter we switch on the heating in our house.” -> “わたし たち は , 家 に あ っ て 熱病 に さ れ て い る の で あ る .” -> “We have a fever at home, " he said.”

“I want to go home” -> “わたし は , 家 に 帰 り ,” -> “I went home,”_

**Comment by jorgtied** [comment]
No, jap (see ISO-639-3) is not the same as ja and I am not sure whether that model works very well in any case. You should not use it for this kind of round-trip translation. Sorry for the confusion.
