### ISSUE TITLE
Docker build fails due to missing libprotobuf23

### ISSUE THREAD

**Issue by Waino** [Helsinki-NLP/Opus-MT#53]
Building the docker image with the command `docker-compose up` fails with the following error:

`E: Unable to locate package libprotobuf23`

`libprotobuf23` is not available in debian buster (it only has libprotobuf17), but it is available from debian buster-backports.

**Comment by santhoshtr** [comment]
See https://github.com/Helsinki-NLP/Opus-MT/issues/44
