### ISSUE TITLE
Translation results using ‘Helsinki-NLP/opus-mt-tc-big-en-ar’ model are not as expected

### ISSUE THREAD

**Issue by alongLFB** [Helsinki-NLP/Opus-MT#86]
![image](https://github.com/Helsinki-NLP/Opus-MT/assets/17883682/579330b2-6cab-43be-8f35-215221739696)

**Comment by alongLFB** [comment]
Helsinki-NLP/opus-mt-en-ar , Using this model, the translation results are as expected.

**Comment by TLOREM** [comment]
Adding to this, I was about to create an issue myself. 
Helsinki-NLP/opus-mt-ar-en also seems to have issues, and I've just found some with chinese too (trying to translate "Chocolate is good.")

Sames to be the same/related issue as you got:
<img width="1605" alt="image" src="https://github.com/Helsinki-NLP/Opus-MT/assets/49133165/055f6e10-f60e-4789-8f79-e90552aa14d6">

**Comment by jorgtied** [comment]
This is (was?) a problem of the models that have been converted to pytorch and huggingface transformers. Please, file issues about those converted models there and not here. Thank you!
