### ISSUE TITLE
What to do with files postprocess.sh, preprocess.sh and source.tcmodel

### ISSUE THREAD

**Issue by dlippold** [Helsinki-NLP/Opus-MT#95]
I downloaded the model _en-de_, i.e. the file `opus-2020-02-26.zip`, from https://github.com/Helsinki-NLP/OPUS-MT-train/tree/master/models/en-de

Therein are the following files: `postprocess.sh`, `preprocess.sh` and `source.tcmodel`

What I have to do with these files? Do I have to name these in the configuration file `services.json`? If yes, in which way?

**Comment by jorgtied** [comment]
Those scripts and models are not supported by the server implementation. You would have to change the server code to integrate them if needed. The tcmodel is probably empty anyway, isn't it?

**Comment by dlippold** [comment]
You are right, the file `source.tcmodel` is empty. Thanks for the information regarding the scripts.
